[project]
name = "sans-pilot"
version = "0.9.0"
description = "MCP server for SANS data analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=3.0.0b1",
    "sans-fitter==0.3.0",
    "bumps==1.0.3",
    "kaleido>=1.2.0",
    "plotly>=6.0",
    "pydantic>=2.0",
    "sasdata>=0.8",
]

[project.optional-dependencies]
dev = [
	"ruff>=0.14.10",
    "pyright>=1.1.408",
	"pytest>=8.0",
]

[project.scripts]
sans-pilot = "sans_pilot.main:main"

[tool.ruff]
target-version = "py312"
line-length = 88
src = ["src"]
indent-width = 2

[tool.ruff.lint]
select = [
    "E",
    "F",
    "B",
    "I",
    "UP"
]
ignore = [
	"E501",   # line too long (handled by formatter)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pyright]
include = ["src", "test"]
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
testpaths = ["test"]
addopts = "-q"
