"""MCP server for SANS data analysis."""

from __future__ import annotations

from fastmcp import FastMCP
from fastmcp.resources import ResourceContent, ResourceResult

from sans_pilot.artifacts import get_published_artifact
from sans_pilot.auth import create_auth_verifier
from sans_pilot.data_tools import register_data_tools
from sans_pilot.example_tools import register_example_tools
from sans_pilot.files import get_user_id_from_request
from sans_pilot.fit_tools import register_fit_tools
from sans_pilot.inversion_tools import register_inversion_tools
from sans_pilot.model_tools import register_model_tools

mcp = FastMCP(
  "sans-pilot",
  auth=create_auth_verifier(),
  instructions="""
SANS (Small-Angle Neutron Scattering) data analysis server.

## Workflow
1. `list-uploaded-sans-files` - Find the user's SANS data files without reading them into model context
2. `list-supported-sans-formats` - Check community-format support when needed
3. `inspect-sans-data` - Inspect an upload, example, or simulation through a typed dataset pipeline
4. `plot-sans-data` - Plot data without selecting or fitting a model
5. `process-sans-data` - Apply ordered arithmetic or Q-range selection and return a reusable file
6. `list-sans-models` - Show exact available model names
7. `get-sans-model-parameters` - Discover parameters for the exact atomic, interacting, or composite model
8. `list-structure-factors` / `get-polydispersity-options` - Discover interaction and size-distribution controls
9. `fit-sans-model` - Run an explicitly weighted optimization or Bayesian fit
10. `scan-sans-dmax` / `invert-sans-pr` - Explore Dmax and recover model-free P(r)
11. `list-sans-examples` / `inspect-sans-example` - Discover curated teaching and validation datasets
12. `simulate-sans-data` / `simulate-sans-pair` - Generate synthetic data with known truth

## Tool Calling Rule
- When the user refers to "my uploaded file(s)", "my data", or the "latest"/"recent" upload without giving an exact stored filename, you MUST call `list-uploaded-sans-files` before responding. Do not claim uploads cannot be listed and do not ask the user to reattach files unless that call returns no compatible files or fails.
- `list-uploaded-sans-files` returns newest first. For "latest file", select the first compatible result. For plural requests, use the returned metadata and original names to identify every requested compatible file, then inspect each selected file.
- If the user explicitly asks to plot, visualize, or inspect data without fitting, call `plot-sans-data`; do not call model-discovery tools or `fit-sans-model`
- Use `pipeline.primary.kind="upload"` for user files, `"example"` for curated datasets, or `"simulation"` for synthetic data
- Never put uploaded file contents into the tool request; pass only the stored filename from `list-uploaded-sans-files`
- Never guess a model or parameter name; use the exact output of `list-sans-models` and `get-sans-model-parameters`

## Low-Friction First Run
- If the user asks for a fit or analysis without specifying a model, do not block for model selection
- Use the latest uploaded SANS data file, inspect it, select an exact model, discover its parameters, and run an initial baseline fit
- An explicit plot-only or no-fit request always overrides the baseline-fit workflow
- Ask follow-up questions only when there is no usable file or tool execution fails

## Key Tools
- `list-structure-factors` - For concentrated samples with particle interactions
- `get-sans-model-parameters` - Also reports which exact parameters support polydispersity
- `pipeline.operations` in `fit-sans-model` - For background subtraction, scaling, and transmission correction
- Composite models support two to five named components, shared parameters, and equality links with BUMPS point-estimate fitting

## Fitting Tips
- Set `vary: true` for parameters to optimize (radius, length, scale, background)
- Use `q_min` and `q_max` to exclude unreliable low- or high-Q regions
- dQ resolution is read automatically when present in the input data
- Use `fit.mode="bayesian"` only when posterior uncertainty analysis is requested; it requires measured dI and an atomic model without parameter links
- For P(r), scan Dmax before inversion when it is not already justified; buffer-subtracted protein data normally uses `fit_background=false`
  """,
)

register_data_tools(mcp)
register_model_tools(mcp)
register_fit_tools(mcp)
register_inversion_tools(mcp)
register_example_tools(mcp)


@mcp.resource(
  "sans-pilot://artifact/{token}",
  name="SANS analysis artifact",
  description="A lazily retrieved artifact generated by a SANS tool call.",
)
def get_sans_artifact(token: str) -> ResourceResult:
  artifact = get_published_artifact(token, user_id=get_user_id_from_request())
  return ResourceResult(
    contents=[
      ResourceContent(
        artifact.path.read_bytes(),
        mime_type=artifact.mime_type,
      )
    ]
  )


def main() -> None:
  mcp.run()
